# history
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=2000

# config
setopt appendhistory 
setopt autocd extendedglob nomatch notify no_beep
setopt prompt_cr prompt_sp

# env vars
export EDITOR='vim'
export KEYTIMEOUT=1
export ANE_REPOROOT="$HOME/repository"

# zle
bindkey -v
bindkey "^r" history-incremental-pattern-search-backward

# zstyle
zstyle :compinstall filename '/home/analyticalnoa/.zshrc'
autoload -Uz compinit
compinit

# prompt
ANE_PROMPTCHAR=◈
PROMPT="%B$ANE_PROMPTCHAR%b "
RPROMPT='%s%B%#%80<..<%~:%n@%M%b (%?)'

# alias
alias rezsh='. ~/.zshrc'
alias retmux='tmux source-file ~/.tmux.conf'
alias ll='ls -alF'

# thefuck
if which thefuck &> /dev/null; then
  eval $(thefuck --alias)
  eval $(thefuck --alias F)
fi

# mux
. ~/.env.conf/shell/comp-mux.zsh
