# history
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=2000

# config
setopt appendhistory 
setopt autocd extendedglob nomatch notify no_beep
setopt prompt_cr prompt_sp

# env vars
export KEYTIMEOUT=1
export ANE_REPOROOT="$HOME/repository"

# zle
bindkey -v
bindkey -v "^r" history-incremental-pattern-search-backward
bindkey -v "^ " push-line-or-edit

# zstyle
zstyle :compinstall filename '/home/analyticalnoa/.zshrc'
autoload -Uz compinit
compinit

# prompt
ANE_PROMPTCHAR=◈
PROMPT="%B%n $ANE_PROMPTCHAR%b "
RPROMPT='%s%B %70<..<%~ %M%b %? %#'

# alias
alias rezsh='. ~/.zshrc'
alias retmux='tmux source-file ~/.tmux.conf'
alias ll='ls -alF'
alias Y='xclip -selection clipboard'
alias P='xclip -selection clipboard -o'
vdp() { # most excilerating recursive function to write, to date.
  if [ -z "$1" ] || [[ $(readlink -f '.') == $(readlink -f "$1") ]]; then
    vdp db
  elif [ ! -d "$1" ]; then
    echo "Bad db."
    return 1
  elif [[ $(dirname "$1") != '.' ]]; then
    pwd_old="$PWD"
    cd $( dirname "$1" )
    vdp ${1/$(dirname "$1")\/}
    cd "$pwd_old"
  elif [ ! -f "$1/.vd" ]; then
    vdp "$1/db"
  else
    vd -p "$1/.vd"
  fi
}

# thefuck
if which thefuck &> /dev/null; then
  eval $(thefuck --alias)
  eval $(thefuck --alias F)
fi

# mux
. ~/.env.conf/shell/comp-mux.zsh

# papis
if which papis &> /dev/null; then
  eval "$(_PAPIS_COMPLETE=source_zsh papis)"
fi
