#! /bin/bash
# papis-short-help: Manage orphan notes

note_path=$( papis -l "$PAPIS_LIB" run echo '$PWD' )/note
old_pwd="$PWD"
default_type=md

__doc__=(
  "usage: papis note -h|--help|help"
  "       papis note edit <note_name>"
  "       papis note pick"
  "       papis note create <note_name>"
  "       papis note list"
)

show_doc() {
  printf '%s\n' "${__doc__[@]}" > /dev/stderr
}

except() {
  echo "$1" > /dev/stderr
  cd "$old_pwd"
  exit 2
}

edit() { # <note_name>
  [ -f "$note_path/$1.$default_type" ] || except "Note not found."
  vim "$note_path/$1.$default_type"
} 

pick() {
  ranger "$note_path"
}

create() { # <note_name>
  [ -z "$1" ] && except "Note name empty."
  vim "$note_path/$1.$default_type"
}

list() {
  ls -1 "$note_path"
}

# main
cd "$note_path"

case $1 in
  -h|--help|help)
    show_doc
    ;;
  edit)
    edit "$2"
    ;;
  pick)
    pick
    ;;
  create)
    create "$2"
    ;;
  list)
    list
    ;;
  *)
    show_doc
    except "Unknown argument."
    ;;
esac

cd "$old_pwd"
