" Author: Noah <abstractednoah@brumal.org>

for c in ["a", "c", "d"]
    exe "set guioptions+=".c
endfor
for c in ["m", "r", "R", "l", "L", "b", "T"]
    exe "set guioptions-=".c
endfor

" vim:ft=vim:fdm=marker:fmr={{{,}}}:fen:tw=80:et:ts=4:sts=4:sw=0:
