set nocompatible
set exrc

"
" Setup vim-plug.
"
" Automatic installation.
" [https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation]
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vimplug')
    Plug 'ctrlpvim/ctrlp.vim'
    Plug 'preservim/nerdtree'
    Plug 'preservim/tagbar'
    Plug '907th/vim-auto-save'
    Plug 'Townk/vim-autoclose'
    Plug 'ludovicchabant/vim-gutentags'
    Plug 'vim-latex/vim-latex', {'for': 'tex'}
    Plug 'tpope/vim-surround'
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    Plug 'honza/vim-snippets'
    Plug 'puremourning/vimspector'
    Plug 'wellle/targets.vim'
call plug#end()

" Called automatically by `plug#end`.
"filetype plugin indent on
"syntax enable


"
" Functions.
" TODO: Should probably be moved to its own plugin directory at some point.
"
function AN_NERDTree()
    " Call `:NERDTreeFind` if path nonempty, otherwise `:NERDTreeVCS`.
    if &modifiable && strlen(expand("%")) > 0 && !&diff
        NERDTreeFind
    else
        NERDTreeVCS
    endif
endfunction

"
" Mapping.
" For most bindings, see 'after/plugin/keys.vim'.
"
let mapleader = ","
set showcmd
set timeoutlen=200

"
" Commands.
"
command ReVim source $MYVIMRC
command RmTrailingWhitespace %s/\s\+$//g

"
" Ecoding.
"
set encoding=utf-8

"
" Ui features.
"
set relativenumber number
set scrolloff=3
set laststatus=2
set statusline=%<%f\ %h%m%r\ %y%=%-14.(%l,%c%V%)\ %P
set foldmethod=syntax
set foldenable
set incsearch hlsearch

"
" Margins: indent, wrap.
"
set colorcolumn=+1
highlight ColorColumn ctermbg=lightgrey guibg=lightgrey
set tabstop=4 expandtab softtabstop=4
set wrap linebreak nolist textwidth=80
set autoindent
set shiftwidth=4

"
" Plugin configuration.
"

" autosave
let g:auto_save = 1
let g:auto_save_in_insert_mode = 0

" NERDTree
let NERDTreeQuitOnOpen = 1

" Coc
source ~/.vim/cocrc.vim

" Vimspector
let g:vimspector_install_gadgets = [
    \ 'debugpy',
    \ 'vscode-cpptools',
    \ 'vscode-java-debug'
\]
" See [https://github.com/puremourning/vimspector#mappings].
nmap <leader>2      <Plug>VimspectorContinue
nmap <leader><c-2>  <Plug>VimspectorStop
nmap <leader>3      <Plug>VimspectorPause
nmap <leader>4      <Plug>VimspectorToggleBreakpoint
nmap <leader><c-4>  <Plug>VimspectorAddFunctionBreakpoint
nmap <leader>5      <Plug>VimspectorStepOver
nmap <leader>6      <Plug>VimspectorStepInto
nmap <leader><c-6>  <Plug>VimspectorStepOut
nmap <leader>0      <Plug>VimspectorRunToCursor
