# zshenv

export PATH="${HOME}/.bin:${HOME}/.local/bin:${PATH}:/opt/jabref/bin"
export EDITOR=vim
export VISUAL=vim
export XDG_DATA_DIRS="${HOME}/.nix-profile/share:${XDG_DATA_DIRS}"

# Make locales work with Nix.
export LOCALE_ARCHIVE="$(readlink ~/.nix-profile/lib/locale)/locale-archive"

# Use nix's Java.
export JAVA_HOME="$(readlink ~/.nix-profile)/lib/openjdk"

# Pin nixpkgs.
export AN_NIXPKGS="https://github.com/abstractednoah/nixpkgs/archive/4678d3c35efc9830bed17c3693ea4d6a588e64ff.tar.gz"
export AN_NIXPKGS_LOCAL="${HOME}/repository/know/explore/cs/nixpkgs"
# NIX_PATH gets overridden by Nix's site-wide profile, which is sourced from
# '/etc/profile', which is sourced from 'zprofile'. For mitigation, see the
# 'nix-env' alias below.
# export NIX_PATH="an_nixpkgs=${AN_NIXPKGS}"

# Enable firefox touch screen scrolling.
export MOZ_USE_XINPUT2=1

# # maven: Fix Java version.
# TODO These aliases shouldn't be necessary since JAVA_HOME is exported above,
# but in that case I'm not sure why I had these lines lol.
# if command -v mvn &> /dev/null; then
#     alias mvn='JAVA_HOME=${JAVA_HOME} mvn'
#     alias mvnDebug='JAVA_HOME=${JAVA_HOME} mvnDebug'
# fi

export GTK_THEME=Adwaita:dark
