#
# Global environment
#

export PATH="${HOME}/.bin:${HOME}/.local/bin:${PATH}"
export EDITOR=vim
export VISUAL=vim
export XDG_DATA_DIRS="${HOME}/.nix-profile/share:${XDG_DATA_DIRS}"

# Make locales work with Nix.
export LOCALE_ARCHIVE="$(readlink ~/.nix-profile/lib/locale)/locale-archive"

# Fix Java version.
export JAVA_HOME="$(readlink ~/.nix-profile)/lib/openjdk"

# Pin nixpkgs.
export AN_NIXPKGS="https://github.com/abstractednoah/nixpkgs/archive/7dfb03161ac23b599b52e552b333132f31acc991.tar.gz"
export AN_NIXPKGS_LOCAL="${HOME}/repository/know/expore/cs/nixpkgs"
# NIX_PATH gets overridden by Nix's site-wide profile, which is sourced from
# '/etc/profile', which is sourced from 'zprofile'. For mitigation, see the
# 'nix-env' alias below.
# export NIX_PATH="an_nixpkgs=${AN_NIXPKGS}"

#
# App-specific environments
#

# firefox: Enable touch screen scrolling.
if command -v firefox &> /dev/null; then
    alias firefox='MOZ_USE_XINPUT2=1 firefox'
fi

# xournalpp: Dark theme.
if command -v xournalpp &> /dev/null; then
    alias xournalpp='GTK_THEME=Adwaita:dark xournalpp'
fi

# maven: Fix Java version.
if command -v mvn &> /dev/null; then
    alias mvn='JAVA_HOME=${JAVA_HOME} mvn'
    alias mvnDebug='JAVA_HOME=${JAVA_HOME} mvnDebug'
fi

# Nix
if command -v nix-env &> /dev/null; then
    alias nix-env-defexpr=$(which nix-env)
    # Yes, it is probably redundant to have both -I and -f.
    alias nix-env='nix-env -I an_nixpkgs=${AN_NIXPKGS} -f ${AN_NIXPKGS}'
fi
