# history
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=2000

# config
setopt appendhistory 
setopt autocd extendedglob nomatch notify no_beep
setopt prompt_cr prompt_sp

# env vars
export KEYTIMEOUT=1
export ANE_REPOROOT="$HOME/repository"

# zle
bindkey -v
bindkey -v "^r" history-incremental-pattern-search-backward
bindkey -v "^ " push-line-or-edit
bindkey -a "^ " push-line-or-edit

# zstyle
zstyle :compinstall filename '/home/analyticalnoa/.zshrc'
autoload -Uz compinit
compinit

# prompt
ANE_PROMPTCHAR=λ
PROMPT_0="%B$ANE_PROMPTCHAR%b "
PROMPT_1='%s%B%n %M %75<..<%~%b %? %#'
NL=$'\n'
PROMPT="${PROMPT_1}${NL}${PROMPT_0}"


# alias
alias rezsh='. ~/.zshrc'
alias retmux='tmux source-file ~/.tmux.conf'
alias ll='ls -alF'
alias Y='xclip -selection clipboard'
alias P='xclip -selection clipboard -o'
alias T='tmux a >&2 2>/dev/null || mux main'
alias R='ranger'
alias v='vim'
alias g='git'
alias d='cambrinary -w'

# thefuck
if which thefuck &> /dev/null; then
  eval $(thefuck --alias)
  eval $(thefuck --alias F)
fi

# mux
. ~/.dotfiles/package/zsh/comp-mux.zsh

# nix
source "$HOME/.zshplugins/nix-zsh-completions/nix-zsh-completions.plugin.zsh"
fpath=("$HOME/.zshplugins/nix-zsh-completions" $fpath)
autoload -U compinit && compinit

# main
[ -z "$TMUX" ] && mux main
