set number

set colorcolumn=81
highlight ColorColumn ctermbg=lightgrey guibg=lightgrey

set incsearch hlsearch

let g:auto_save = 1
let g:auto_save_in_insert_mode = 0

set tabstop=4 expandtab softtabstop=2
set wrap linebreak nolist textwidth=80
set autoindent
