#!/bin/bash

# GLOBALS {{{1
esc_key="<Ctrl-[>"
toggle_key="<Shift-Escape>"

# FUNCTIONS {{{1

# print_usage() - Print usage statement to stdout. {{{2
print_usage() {
    cat <<EOF
usage: $0 (help|leave|passthru)

Qutebrowser userscript for toggling the behavior of <Ctrl-[> in passthrough mode
via <Shift-Escape>.

help
    Print this message and exit.
leave
    Emit command that binds <Ctrl-[> to 'mode-leave' and toggle <Shift-Escape>.
passthru
    Emit command that binds <Ctrl-[> to 'fake-key <Escape>' and toggle
    <Shift-Escape>.
EOF
}

# oops(message, ...) - Print error and usage to stderr then exit with 1. {{{2
oops() {
    echo "${0}:" "${@}" >&2
    print_usage >&2
    exit 1
}

# send_cmd(command, ...) - Send command to qutebrowser. {{{2
# Command may be split into args, they will be joined with spaces.
send_cmd() {
    echo "${@}" >> "${QUTE_FIFO}"
}

# MAIN {{{1

while [ "${#}" -gt 0 ]
do
    case "${1}" in
        --help|-h|help)
            print_usage
            exit 0
            ;;
        leave)
            send_cmd "bind --mode passthrough ${esc_key} mode-leave"
            send_cmd "bind --mode passthrough ${toggle_key}" \
                "spawn --userscript toggle-esc passthru"
            exit 0
            ;;
        passthru)
            send_cmd "bind --mode passthrough ${esc_key} fake-key <Escape>"
            send_cmd "bind --mode passthrough ${toggle_key}" \
                "spawn --userscript toggle-esc leave"
            exit 0
            ;;
        *)
            oops "Unrecognized option: ${1}"
            ;;
    esac
done


# vim:ft=bash:tw=80:et:ts=4:sts=4:sw=0:fdm=marker:fmr={{{,}}}:fen:
