#!/bin/bash

_self=$(readlink -f "${0}")

_command="${1}"
_arg="${2}"

case ${_command} in
    lock)
        ~/.dotfiles/share/lock
        ;;
    exit)
        i3-nagbar -t warning -m 'Exit i3wm?' -b 'Yeah.' 'i3-msg exit'
        ;;
    shutdown)
        i3-nagbar -t warning -m 'Shutdown?' -b 'Yeah.' 'shutdown now'
        ;;
    reboot)
        i3-nagbar -t warning -m 'Reboot?' -b 'Yeah.' 'shutdown -r now'
        ;;
    hibernate)
        i3-input -F "exec ${_self} _hibernate %s" -P "hibernate? [yN] "
        ;;
    _hibernate)
        if [ "${_arg}" = y ]; then
            ${_self} lock &
            systemctl hibernate
        fi
        ;;
    reload)
        i3-msg reload
        ;;
    restart)
        i3-msg restart
        ;;
    notify_pause)
        if pgrep -xc dunst; then
            killall -q -SIGUSR1 dunst
        fi
        ;;
    notify_resume)
        if pgrep -xc dunst; then
            killall -q -SIGUSR2 dunst
        fi
        ;;
    *)
        exit -1
        ;;
esac
