#!/usr/bin/env bash

_image_path="${HOME}/.wallpaperlock"

_get_bar_mode() {
    i3-msg -t get_bar_config bar-0 | jq -r .mode
}

_old_bar_mode=$(_get_bar_mode)

_pre_lock() {
    ~/.dotfiles/share/control-system notify_pause \
        && i3-msg bar mode invisible
}

_post_lock() {
    i3-msg bar mode "${_old_bar_mode}"
    ~/.dotfiles/share/control-system notify_resume
}

_lock() {
    i3lock \
        --dpms --inactivity-timeout 10 \
        --tiling --image="${_image_path}" \
        --nofork
}

_pre_lock \
    && _lock
_post_lock
